### ISSUE TITLE
Running into undefined Errors.

### ISSUE THREAD

**Issue by skullr34p3r** [Jromero1208/RangerBasediRF#1]
Please see attached for more info on the problem. The issue is that when running the 'make' command I am failing out with multiple undefined errors. Any assistance would be greatly appreciated.
[RangerOutput.txt](https://github.com/Jromero1208/RangerBasediRF/files/3879979/RangerOutput.txt)

**Comment by AshleyCliff** [comment]
What compiler is being used? Would it be possible to list the output from the cmake command? It looks like the MPI library isn't being connected, which requires use of specific compilers.

Could you also provide the system architecture that you are trying to get this compiled for?

**Comment by skullr34p3r** [comment]
Hello Ashley,

I am running this with gcc-c++.x86_64 on my CentOS 7.7.1908 VM.

When originally running the cmake command I was running into a library issue, the only way around it was to run 'CPATH=/usr/include/openmpi-x86_64/ make' After running this command it has kept the environment variable set and not required me to use it again. The issue before is that the compiler could not see mpi.h.

If I run 'make clean' it will give me this error:
'[root@****** build]# make
[  5%] Building CXX object CMakeFiles/ranger.dir/src/Forest/Forest.o
In file included from /tmp/JAC/RangerBasediRF-master/cpp_version/src/Forest/Forest.cpp:42:0:
/usr/include/mpi.h:258:39: fatal error: mpi_portable_platform.h: No such file or directory
 #    include "mpi_portable_platform.h"
                                       ^
compilation terminated.
make[2]: *** [CMakeFiles/ranger.dir/src/Forest/Forest.o] Error 1
make[1]: *** [CMakeFiles/ranger.dir/all] Error 2
make: *** [all] Error 2'

Which forces me to run 'CPATH=/usr/include/openmpi-x86_64/ make' again to get to this point. I believe you are right in the fact that the libraries are not being connected/utilized properly, but I am unsure as to why this is happening.

Cheers,
Justin

**Comment by AshleyCliff** [comment]
Can you list the output of the cmake command.

**Comment by skullr34p3r** [comment]
[root@****** build]# cmake ..
Compiler with C++11 support found.
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/JAC/RangerBasediRF-master/cpp_version/build

**Comment by AshleyCliff** [comment]
What version of cmake are you using? Your cmake output is very different from all the output shown in mine, which includes the system looking for and finding the compilers. 

The open-mpi library should have come with compiler wrappers, mpiCC and mpicc. If you have those, you may want to set them explicitly in the cmake command:

cmake -DCMAKE_CXX_COMPILER=mpiCC -DCMAKE_C_COMPILER=mpicc ..

I should mention that this code has only been compiled on a few HPC systems at this point, and is not guaranteed to function on all systems. It is still in early beta.

**Comment by AshleyCliff** [comment]
I would suggest completely removing the build directory and starting from scratch. That cmake output is what appears if cmake has already been run.

**Comment by skullr34p3r** [comment]
[root@****** build]# cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
Compiler with C++11 support found.
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/JAC/RangerBasediRF-master/cpp_version/build

**Comment by AshleyCliff** [comment]
Based on the cmake output, it doesn't look like a MPI compatible compiler is being used. I would suggest reading through this: https://www.open-mpi.org/faq/?category=mpi-apps 

and running cmake with:

cmake -DCMAKE_CXX_COMPILER=mpiCC -DCMAKE_C_COMPILER=mpicc ..

**Comment by skullr34p3r** [comment]
I took your advice and removed the build directory and re-added it. Then ran 'cmake -DCMAKE_CXX_COMPILER=mpiCC -DCMAKE_C_COMPILER=mpicc ..' followed by 'make' and it has resolved my issue.
Thank you for the support.

Cheers,
Justin

**Comment by AshleyCliff** [comment]
Great! Let us know if you have other questions.
